<?php

namespace Plugin\BannerManagement4\Repository;

use Doctrine\ORM\EntityRepository;
use Eccube\Repository\AbstractRepository;
use Plugin\BannerManagement4\Entity\BannerField;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * BannerFieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerFieldRepository extends AbstractRepository
{
    /**
     *  constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(
        RegistryInterface $registry
    )
    {
        parent::__construct($registry, BannerField::class);

    }
}
