<?php

namespace Plugin\BannerManagement4\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BannerFieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerFieldRepository extends EntityRepository
{
}
